---
- name: Initial config a linux machine
  hosts: all
  vars_files: "vars/ansible_user.vault.yaml"
  become: yes
  tasks:
  
  - name: Create ansible user on Red Hat based host
    user:
      name: "{{ ansible.username }}"
      password: "{{ ansible.password | password_hash('sha512') }}"
      group: wheel
      append: yes
    when: ansible_os_family == "RedHat"

  - name: Create ansible user on Debian based host
    user:
      name: "{{ ansible.username }}"
      password: "{{ ansible.password | password_hash('sha512') }}"
      group: sudo
      append: yes
    when: ansible_os_family == "Debian"

  - name: Copy ansible user ssh key
    authorized_key:
      user: "{{ ansible.username }}"
      key: "{{ ansible.authorized_key }}"
