---
- name: Initial config a linux machine
  hosts: all
  vars_files: "vars/ansible_user.vault.yaml"
  tasks:

  - name: Create ansible user on Red Hat based host
    user:
      name: "{{ ansible.username }}"
      password: "{{ ansible.password | password_hash('sha512') }}"
      group: wheel
      append: yes
    when: ansible_os_family == "RedHat"

  - name: Create ansible user on Debian based host
    user:
      name: "{{ ansible.username }}"
      password: "{{ ansible.password | password_hash('sha512') }}"
      group: sudo
      append: yes
    when: ansible_os_family == "Debian"

  - name: Copy ansible user ssh key
    authorized_key:
      user: "{{ ansible.username }}"
      key: "{{ ansible.authorized_key }}"

  - name: Upgrade Red Hat based hosts
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat" and skip_update is not defined
    notify: reboot host

  - name: Upgrade Debian based hosts
    apt:
      force_apt_get: yes
      name: '*'
      state: latest
      update_cache: yes
      autoremove: yes
    when: ansible_os_family == "Debian"
    notify: reboot host

  handlers:

  - name: reboot host
    reboot:
