---
- name: Initial config of Windows machines
  hosts: all
  tasks:

  - name: Create ansible user
    win_user:
      name: "{{ ansible_user['username'] }}"
      fullname: 'Ansible User'
      gourps: administrator
      password: "{{ ansible_user['password'] }}"
      password_expired: no
      password_never_expires: yes
      account_disabled: no
      account_locked: no
